# Generated by Django 2.1.3 on 2018-11-11 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_drink_menus', models.IntegerField(default=0)),
                ('res_datetime', models.DateTimeField(verbose_name='date and of reservation')),
                ('res_duration', models.IntegerField(default=120)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Locations')),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Reservations')),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.PaymentTypes'),
        ),
        migrations.AddField(
            model_name='locations',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Space'),
        ),
        migrations.AddField(
            model_name='employees',
            name='emp_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Roles'),
        ),
    ]
