# Generated by Django 2.1.3 on 2018-11-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='name',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
